"""
Django settings for myproject14 project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

# ========================
# المسارات الأساسية
# ========================
BASE_DIR = Path(__file__).resolve().parent.parent


# ========================
# إعدادات الأمان
# ========================
SECRET_KEY = 'django-insecure-0xj_nhbg(gm$@p1+vts&b=x82!&2jyxr+s^j9wa1p=zz%)y6^5'

DEBUG = True  # ⚠️ يجب جعله False عند رفع المشروع للسيرفر

ALLOWED_HOSTS = []


# ========================
# التطبيقات
# ========================
INSTALLED_APPS = [
    # تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ========================
    # تطبيقات المشروع
    # ========================
    'core',
    'products',
    'orders',
]


# ========================
# الميدلوير
# ========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # دعم اللغات (تعريب)
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ========================
# روابط المشروع
# ========================
ROOT_URLCONF = 'myproject14.urls'


# ========================
# القوالب
# ========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # مجلد القوالب
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ========================
# WSGI
# ========================
WSGI_APPLICATION = 'myproject14.wsgi.application'


# ========================
# قاعدة البيانات
# ========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ========================
# التحقق من كلمات المرور
# ========================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ========================
# اللغة والتوقيت
# ========================
LANGUAGE_CODE = 'ar'        # ❗ اللغة العربية
TIME_ZONE = 'Asia/Riyadh'   # ❗ توقيت الرياض

USE_I18N = True
USE_TZ = True


# ========================
# الملفات الثابتة
# ========================
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # عند الرفع للسيرفر


# ========================
# ملفات الوسائط (إن وجدت)
# ========================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ========================
# النهاية
# ========================
