"""
Django settings for myproject14 project.
Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path

# ========================
# المسارات الأساسية
# ========================
BASE_DIR = Path(__file__).resolve().parent.parent


# ========================
# إعدادات الأمان
# ========================
SECRET_KEY = 'django-insecure-0xj_nhbg(gm$@p1+vts&b=x82!&2jyxr+s^j9wa1p=zz%)y6^5'

DEBUG = True  # ⚠️ اجعله False عند الإنتاج

ALLOWED_HOSTS = []


# ========================
# التطبيقات
# ========================
INSTALLED_APPS = [
    # تطبيقات Django الأساسية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ========================
    # تطبيقات المشروع
    # ========================
    'core.apps.CoreConfig',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
]


# ========================
# الميدلوير
# ========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # 🌍 دعم اللغة العربية
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ========================
# روابط المشروع
# ========================
ROOT_URLCONF = 'myproject14.urls'


# ========================
# القوالب (Templates)
# ========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # مجلد القوالب العام
        'DIRS': [
            BASE_DIR / 'templates',
        ],

        # قوالب داخل التطبيقات
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ========================
# WSGI
# ========================
WSGI_APPLICATION = 'myproject14.wsgi.application'


# ========================
# قاعدة البيانات
# ========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ========================
# التحقق من كلمات المرور
# ========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ========================
# اللغة والتوقيت
# ========================
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True
USE_TZ = True


# ========================
# الملفات الثابتة (Static Files)
# ========================
STATIC_URL = '/static/'

# المجلد الذي أنشأته يدويًا
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# مجلد التجميع للإنتاج
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ========================
# ملفات الوسائط (Media Files)
# ========================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ========================
# الإعداد الافتراضي للمفاتيح
# ========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
